//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tranzit_Waybills_OS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceList
    {
        public System.Guid Id { get; set; }
        public Nullable<int> ShopId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
