//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tranzit_Waybills_OS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaybillDet
    {
        public int PosId { get; set; }
        public System.DateTime OnDate { get; set; }
        public decimal Amount { get; set; }
        public decimal Price { get; set; }
        public int ProductId { get; set; }
        public int ShopId { get; set; }
        public string DocNum { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<int> WbillId { get; set; }
        public Nullable<System.DateTime> ShipmentDate { get; set; }
        public Nullable<int> CompanyId { get; set; }
    }
}
