//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tranzit_OS
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SESS
    {
        public int SESSID { get; set; }
        public int SYSTEMID { get; set; }
        public int SAREAID { get; set; }
        public string SESSSTART { get; set; }
        public string SESSEND { get; set; }
    }
}
